# Generated by Django 3.1.3 on 2020-12-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(max_length=30)),
                ('guestEmail', models.CharField(max_length=30)),
                ('guestContact', models.CharField(max_length=30)),
                ('guestMessage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('projectImage', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=100)),
                ('projectLink', models.CharField(max_length=100)),
            ],
        ),
    ]
